docs: add agenda for 2019-10-22
hamburg-js/minutes pull request #8
Opened 2019-10-22 11:45 UTC by ZauberNerd

2019-10-22 12:03 UTC, herschel666 commented on 2019-10-22.md
> +### Reflection of the last meetup (Finanzcheck)
The last meetup has been at Wunder.

2019-10-22 16:29 UTC, learosema submitted a review, later dismissed

2019-10-23 08:49 UTC, ZauberNerd commented
Meeting minutes have been added. Please review again @hamburg-js/organizers

2019-10-23 09:01 UTC, agalliat submitted a review, later dismissed

2019-10-23 09:14 UTC, ZauberNerd commented on 2019-10-22.md
> +- __(d)__ We will try to be more aware of than, when that happens and redirect it to the break after the Q&A has ended
```suggestion
- __(d)__ We will try to be more aware of these situations and when they happen redirect them to conversions during the breaks
```

2019-10-23 09:21 UTC, agalliat submitted a review, later dismissed

2019-10-23 12:02 UTC, herschel666 requested changes
found one typo.

2019-11-05 12:04 UTC, herschel666 commented on 2019-10-22.md
> +- __(d)__ We will try to be more aware of these situations and when they happen redirect them to conversions during the breaks
```suggestion
- __(d)__ We will try to be more aware of these situations and when they happen redirect them to conversations during the breaks
```

2019-11-05 12:05 UTC, herschel666 approved these changes

2019-11-05 12:06 UTC, merged